//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSMS6.Admin
{


    public partial class View_Orders
    {

        /// <summary>
<<<<<<< HEAD
        /// OrderStatus control.
=======
        /// ddlOrder control.
>>>>>>> 7015187b99ebf96f1ff779330de665e08c66bcb2
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.DropDownList OrderStatus;
=======
        protected global::System.Web.UI.WebControls.DropDownList ddlOrder;
>>>>>>> 7015187b99ebf96f1ff779330de665e08c66bcb2

        /// <summary>
        /// AllorderTableRecord control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater AllorderTableRecord;
    }
}
